# @package _group_
init:
  _target_: gnosis.datasets.IMDB
  root: ${dataset_dir}/imdb
  download: False

name: imdb
num_classes: 2
subsample:
  ratio: 1.0
  seed: 0
  split: 0
min_freq: 10
max_len: 100
